name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  # pass an environment variable to Cypress
  # a test can get its value like this
  # Cypress.env('environmentName') // 'staging'
  # see https://on.cypress.io/env
  CYPRESS_environmentName: staging

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
