name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: humaniaregistry.azurecr.io
          username: humaniaregistry
          password: 9qDq6QX3OPdlE1zpGJh8o1JcmPi=0KeO
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            version=1
          tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}

